/*
 * SharedLink
 *
 * SharedLink服务对外开放的RESTful API集合    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sharedlink

type LinkTypeAndLinkId struct {
	// SharedLink唯一标识
	Id string `json:"id"`
	// SharedLink类型： - `realname` 实名共享 - `anonymous` 匿名共享 
	Type_ string `json:"type"`
}
