/*
 * SharedLink
 *
 * SharedLink服务对外开放的RESTful API集合    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sharedlink

type AddItemInfoDocumentRealname struct {
	// 被共享对象的类型
	Type_ string `json:"type"`
	// 被共享对象的唯一标识
	Id string `json:"id"`
}
