/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type FileOsenduploadReq struct {
	// 文件的CRC32校验码
	Crc32 string `json:"crc32,omitempty"`
	// 文件gns路径（创建协议返回）
	Docid string `json:"docid"`
	// 文件MD5值
	Md5 string `json:"md5,omitempty"`
	// 文件的slice_md5
	SliceMd5 string `json:"slice_md5,omitempty"`
	// 文件版本号
	Rev string `json:"rev"`
	// 文件密级，仅上传定密时需要设置  - 0：默认值，创建文件时文件密级设为创建者密级，覆盖版本时不改变密级  - 5~15：正常密级  - 0x7FFF：空密级  
	Csflevel int64 `json:"csflevel,omitempty"`
	// 表示编辑文件时，基于文件的哪个版本（版本ID）进行编辑，默认为空。  - 如果为空，不检查是否基于文件的最新版本进行编辑；  - 如果不为空，若所编辑的版本ID不是服务器上文件的最新版本，则上传报错。错误码403203，“所编辑文件的版本与服务端文件最新版本不一致”；  
	Editedrev string `json:"editedrev,omitempty"`
}
