/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type DirCreateRes struct {
	// 创建的目录的gns路径
	Docid string `json:"docid"`
	// 数据变化标识
	Rev string `json:"rev"`
	// 创建时间，UTC时间，此为服务器时间
	Modified int64 `json:"modified"`
	// 目录创建的服务端时间
	CreateTime int64 `json:"create_time"`
	// 目录创建者
	Creator string `json:"creator"`
	// 目录修改者
	Editor string `json:"editor"`
	// UTF8编码，仅当ondup为2时才返回
	Name string `json:"name,omitempty"`
}
