/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type DirListReq struct {
	// 要浏览的目录的gns路径
	Docid string `json:"docid"`
	// 指定按哪个字段排序    若不指定，默认按docid升序排序    说明：  - name，按文件名称（中文按拼音）排序  - size，按大小排序（目录按name升序）  - time，按服务器修改时间排序  
	By string `json:"by,omitempty"`
	// 升序还是降序，默认为升序    说明：  - asc，升序  - desc，降序  
	Sort string `json:"sort,omitempty"`
}
