/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type DirListResDir struct {
	// 目录中文件/目录的gns路径
	Docid string `json:"docid"`
	// 目录中文件/目录的名称，UTF8编码
	Name string `json:"name"`
	// 目录中文件版本号或目录数据变化标识
	Rev string `json:"rev"`
	// 目录中文件的大小，目录大小为-1
	Size int64 `json:"size"`
	// 目录/文件创建的服务端时间
	CreateTime int64 `json:"create_time"`
	// 目录/文件创建者
	Creator string `json:"creator"`
	// 目录修改时间/文件上传时间，UTC时间，此为文件上传到服务器时间
	Modified int64 `json:"modified"`
	// 目录修改者/文件编辑者
	Editor string `json:"editor"`
	// 如果是文件，返回由客户端设置的文件本地修改时间    若未设置，返回modified的值  
	ClientMtime int64 `json:"client_mtime,omitempty"`
	// 文件密级  - 0：默认值，创建文件时文件密级设为创建者密级，覆盖版本时不改变密级  - 5~15：正常密级  - 0x7FFF：空密级  
	Csflevel int64 `json:"csflevel"`
	// 文件到期提醒时间
	Duedate int64 `json:"duedate"`
}
