/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type UserGetRes struct {
	// 用户唯一标识
	Userid string `json:"userid"`
	// 用户登录账号
	Account string `json:"account"`
	// 用户显示名
	Name string `json:"name"`
	// 用户邮箱地址
	Mail string `json:"mail"`
	// 用户密级，5~15
	Csflevel int64 `json:"csflevel"`
	// 防泄密配置  0表示不允许打印，也不允许拷屏  1表示允许打印  2表示允许拷屏  3表示允许打印/拷屏
	Leakproofvalue int64 `json:"leakproofvalue"`
	// 是否开启管控密码  1 表示开启  0 表示关闭
	Pwdcontrol int64 `json:"pwdcontrol"`
	// 用户类型  1 表示本地用户  2 表示域用户  3 表示第三方认证用户
	Usertype int64 `json:"usertype"`
	// 用户的多个直属部门信息
	Directdepinfos []UserGetResDirectdeptinfo `json:"directdepinfos"`
	// 是否需要二次认证
	Needsecondauth bool `json:"needsecondauth"`
	// 冻结状态 true：冻结 false：未冻结
	Freezestatus bool `json:"freezestatus"`
	// 同意使用协议状态 true：同意  false：未同意
	Agreedtotermsofuse bool `json:"agreedtotermsofuse"`
	// 是否为组织管理员
	Ismanager bool `json:"ismanager"`
	// 用户手机号
	Telnumber string `json:"telnumber"`
	// 用户是否需实名认证 true：需要 false : 不需要
	Needrealnameauth bool `json:"needrealnameauth"`
	// 所属角色，整数数组，每个整数表示不同的角色  1：表示文档审核员  [1]
	Roletypes []int64 `json:"roletypes"`
	// 用户角色信息
	Roleinfos []UserGetResRoleinfo `json:"roleinfos"`
}
