/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type FileRenameReq struct {
	// 要重命名的文件gns路径
	Docid string `json:"docid"`
	// 重命名成功后的新文件名，UTF8编码
	Name string `json:"name"`
	// - 1:检查是否重命名，重名则抛异常  - 2:如果重名冲突，自动重名  
	Ondup int64 `json:"ondup,omitempty"`
}
