/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

import (
	"time"
)

// 文档信息
type EntryItem struct {
	// 文档名称
	Name string `json:"name"`
	// 文档变化标识
	Rev string `json:"rev"`
	// 创建的服务端时间(秒级)，RFC3339格式
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *User     `json:"created_by"`
	// 修改时间/文件上传时间(秒级)，RFC3339格式
	ModifiedAt time.Time `json:"modified_at"`
	ModifiedBy *User     `json:"modified_by"`
	// 文档类型：  - file：文件   - folder：文件夹
	Type_ string `json:"type"`
	// 文档库类型：  - user_doc_lib：个人文档库   - department_doc_lib：部门文档库   - custom_doc_lib：自定义文档库
	DocLibType string `json:"doc_lib_type"`
	// 文档id
	Id string `json:"id"`
	// 文件大小
	Size int64 `json:"size,omitempty"`
}
