/*
 * 文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package efast

type FileOsdownloadReq struct {
	// 文档id
	Docid string `json:"docid"`
	// 文件版本号，为空默认下载最新版本
	Rev string `json:"rev,omitempty"`
	// 默认为空，在header中包含鉴权，否则在url中包含鉴权。QUERY_STRING，url中包含鉴权
	Authtype string `json:"authtype,omitempty"`
	// 使用QUERY_STRING方式下载时（浏览器），可以设置要保存的文件名
	Savename string `json:"savename,omitempty"`
}
