/*
 * OAuth 2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package oauth2

type CreateClientSuccess struct {
	// 此客户端的ID。
	ClientId string `json:"client_id"`
	// secret是客户端的secret。secret将以明文形式包含在创建请求中，然后再也不会包含。secret使用BCrypt存储，因此无法恢复。对于客户端，他们需要写下secret，因为secret将不会再被返回。
	ClientSecret string `json:"client_secret"`
}
