/*
 * OAuth 2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package oauth2

// 设备信息
type Device struct {
	// 设备名称
	Name string `json:"name,omitempty"`
	// 客户端类型
	ClientType string `json:"client_type"`
	// 设备描述，自定义。如： iphone5s ipad 联想一体机 mac
	Description string `json:"description,omitempty"`
}
